# Generated by Django 5.2.1 on 2025-05-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expresion', models.CharField(max_length=255)),
                ('metodo', models.CharField(default='secante', max_length=50)),
                ('resultado', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
